### ISSUE TITLE
Uniswap

### ISSUE THREAD

**Issue by terrorist96** [aneonex/BitcoinChecker#30] opened 2020-11-20 17:20 UTC
Not sure if you can add Uniswap, but worth asking.

**Comment by aneonex** [comment] 2020-11-22 09:05
Uniswap is decentralized exchange (DEX) that requires a different technology than centralized exchanges to get pairs/price.
The implementation of DEX to Bitcoin Checker seems very complicated.
I think the most simple way to add Uniswap info is to use third party service - CoinGeko (https://www.coingecko.com/en/exchanges/uniswap/). But CoinGeko allows to get price for pairs with ETH only. 
Would such an implementation be useful?

**Comment by terrorist96** [comment] 2020-11-22 14:34
I think anything would be better than nothing. Thanks 😀

**Comment by aneonex** [comment] 2020-11-24 22:56
Uniswap will be added in the next app release.

**Comment by terrorist96** [comment] 2020-11-27 22:50
Some coins aren't visible like:
https://www.coingecko.com/en/coins/meme
Also the second coin (ETH) is shown twice in the list.

**Comment by terrorist96** [comment] 2020-11-27 22:58
Also, such links can't be utilized?
https://info.uniswap.org/pair/0x5DFbe95925FFeb68f7d17920Be7b313289a1a583

**Comment by aneonex** [comment] 2020-11-28 00:06
> Some coins aren't visible like:
> https://www.coingecko.com/en/coins/meme

This is strange. I don't understand why CoinGecko UI is showing information, but the API is not returning these coins. It takes time to research...

> Also the second coin (ETH) is shown twice in the list.

Can you describe in more detail? Is this with all the pairs? I can't reproduce this.

**Comment by aneonex** [comment] 2020-11-28 00:33
>Also, such links can't be utilized?
https://info.uniswap.org/pair/0x5DFbe95925FFeb68f7d17920Be7b313289a1a583

This is targeted info, but the API has a different technology that requires a lot of refactoring in the data module. This can be implemented in the future.

**Comment by terrorist96** [comment] 2020-11-28 00:56
![Screenshot_20201127-195609_Bitcoin Checker](https://user-images.githubusercontent.com/12802056/100490616-a134ba80-30ea-11eb-80ed-4fd5abb1e1dc.jpg)

**Comment by terrorist96** [comment] 2020-11-28 00:59
I think Uniswap has different lists of coins and there are two CoinGecko lists, but some coins aren't in any list and require you to input the contract address in Uniswap to make it appear. This could be why some coins aren't visible.

**Comment by aneonex** [comment] 2020-11-28 01:13
I will exclude Uniswap from app release to take time to fixes and research.
Thank you for operational feedback.

**Comment by terrorist96** [comment] 2020-11-28 01:23
I think you could keep it for now while you improve it. It's not 100% but like 90% and that's better than 0%. 😃

**Comment by aneonex** [comment] 2020-11-28 01:35
Unstable behavior will raise questions and negative user reviews.

**Comment by aneonex** [comment] 2020-11-29 18:39
Now Uniswap pairs are loaded just like info.uniswap.org from thegraph.com. All previous issues will be resolved.
All changes will be included in the latest app v2.18.

P.S.
Google is slow to publish the latest app updates :(

**Closed by aneonex** 2020-11-29 18:39 UTC
Labels: enhancement

**Comment by terrorist96** [comment] 2020-11-29 18:55
It says only the top 500 most liquid pairs will be shown, so the example coin I sent above still won't work?

**Comment by aneonex** [comment] 2020-11-29 19:26
MEME coin included to the top and will be listed in the app.

You can check the top 500 Uniswap pairs yourself:
1) Open in browser url: https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2/
2) Copy next query to the left window: 
{pairs(first: 500, orderBy:reserveUSD, orderDirection:desc) {reserveUSD token0{symbol} token1{symbol}}}
3) Push execute button

The app using same API.

**Comment by terrorist96** [comment] 2020-11-30 02:56
Great, thanks! There is also a telegram uniswap price bot; I wonder if they use thegraph.com. See https://t.me/UniSwapPriceBot. There's also dedicated bots that show trading data for specific listing pairs. See: https://unibot.network/
This is all just FYI.
