### ISSUE TITLE
Can't add widget with Apex launcher classic

### ISSUE THREAD

**Issue by oslo33** [aneonex/BitcoinChecker#183] opened 2022-01-11 10:25 UTC
Hi,

I have Apex launcher classic. When i try to add the widget Bitcoin checker i can't and i have the message "The appliction is not installed". Of course the application is installed.

As soon as i quit apex launcher classic and use the native launcher of my Oneplus6T i can install the widget Bitcoin checker and all is working fine.

Is it possible to make the widget working with apex launcher classic?
Thanks

**Comment by aneonex** [comment] 2022-01-11 16:51
This looks like a duplicate of the issue #177 . This should be resolved in the next 2.51 app release.
What version of the app do you have?

**Comment by oslo33** [comment] 2022-01-11 17:01
The apex launcher classic is the V3.4.5
The bitcoin checker is the V2.50.1

**Comment by aneonex** [comment] 2022-01-11 17:07
Yes, it is the same, will be fixed in v2.51.
New release rollout already started. All users will receive within 1-2 days.

**Comment by aneonex** [comment] 2022-01-13 16:34
Updated app version 2.51 is available in Google Play. Is your issue solved?

**Closed** 2022-01-15 09:00 UTC
