### ISSUE TITLE
Notifications vibrate even when phone is in silent mode

### ISSUE THREAD

**Issue by bobanm** [aneonex/BitcoinChecker#215] opened 2022-07-19 20:50 UTC
When I switch my phone to silent mode [which disables vibration], Bitcoin Checker is the only app whose notifications are still vibrating.

When I want to stay online, but want my phone to be absolutely silent, I either need to switch off individual alerts for every single pair, or to force stop the app, and restart it when I'm ready to resume with receiving vibrating notifications.

I recall clearly that this wasn't the issue with the original Bitcoin Checker from Mobnetic.

**Comment by aneonex** [comment] 2022-07-19 22:10
This has now been fixed and will be included in the next app release v2.58 (~1 week).
Thank you for the feedback.

P.S.
The issue is related to significant changes in the requirements for notifications in the latest versions of Android. Notifications in Bitcoin Checker have been completely redesigned since the legacy app.

**Closed by aneonex** 2022-07-19 22:10 UTC
